name: Command via SSH

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: copy via SSH
        uses: garygrossgarten/github-action-scp@release
        with:
          local: www
          remote: .
          host: ${{ secrets.HOST }}
          username: garygrossgarten
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}

        env:
          CI: true
